version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    image: app_service
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 88:80
      - 443:443
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network


  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - 1306:3306
    environment:
      MYSQL_DATABASE: task
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

# for dev
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

